services:
  backend:
    build:
      context: ./Back-end
      dockerfile: ./Back-end/Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: sqlite:/data/db/mydb.sqlite
    volumes:
      - ./Back-end:/app
    depends_on:
      - db

  frontend:
    build:
      context: ./Front-end
      dockerfile: ./Front-end/Dockerfile
    ports:
      - "3000:3000"
    working_dir: /app
    command: ["bun", "run", "server.ts"]  
    environment:
      REACT_APP_BACKEND_URL: http://localhost:8000
    depends_on:
      - backend

  db:
    image: nouchka/sqlite3
    volumes:
      - sqlite_data:/data/db

volumes:
  sqlite_data:
